# Generated by Django 5.0.3 on 2024-08-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='department', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='Block', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='phone', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='feed_back',
            field=models.TextField(blank=True, default='', max_length=600),
        ),
    ]
