# Generated by Django 5.0.3 on 2024-08-17 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_description_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
