# Generated by Django 5.0.3 on 2024-08-17 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_request_assigned_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
