# Generated by Django 5.0.3 on 2025-02-15 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_request_assigned_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'farmer'), ('client', 'client')], default='client', max_length=100, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product_name', models.CharField(max_length=200)),
                ('order_product_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_product_category', models.CharField(max_length=20)),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('order_client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_order', to=settings.AUTH_USER_MODEL)),
                ('order_farmer', models.ForeignKey(blank=True, limit_choices_to={'role': 'farmer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=20)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_farmer', models.ForeignKey(blank=True, limit_choices_to={'role': 'farmer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
