# Generated by Django 5.0.3 on 2025-02-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_department_customuser_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
