# Generated by Django 5.0.3 on 2025-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_orders_order_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('client', 'Client')], default='client', max_length=100, verbose_name='Role'),
        ),
    ]
