# Generated by Django 5.0.3 on 2025-02-19 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_farmer',
            new_name='farmer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_farmer',
            new_name='farmer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product_category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_created',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'buyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Farmer', 'farmer'), ('Buyer', 'buyer')], default='Buyer', max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.CharField(max_length=100),
        ),
    ]
