# Generated by Django 5.0.3 on 2025-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_order_farmer_order_farmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], default='Buyer', max_length=100, verbose_name='Role'),
        ),
    ]
