# Generated by Django 5.0.3 on 2025-02-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
    ]
