# Generated by Django 5.0.3 on 2025-02-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
