# Generated by Django 5.0.3 on 2025-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
