# Generated by Django 5.0.3 on 2025-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_cart_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_category',
            field=models.CharField(default='category', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_name',
            field=models.CharField(default='order', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
