# Generated by Django 5.0.3 on 2025-02-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_name',
            field=models.CharField(max_length=200),
        ),
    ]
