# Generated by Django 5.0.3 on 2025-03-06 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_customuser_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_product_name', models.CharField(max_length=200)),
                ('paid_product_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('paid_product_category', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(max_length=200, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('buyer', models.ForeignKey(blank=True, limit_choices_to={'role': 'buyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_paid_product', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(blank=True, limit_choices_to={'role': 'farmer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_paid_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
