# Generated by Django 5.0.3 on 2025-03-11 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_agreed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paid',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paid',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='product_id', max_length=200),
        ),
    ]
