# Generated by Django 5.0.3 on 2025-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_cart_ordered_at_customuser_is_agreed_paid_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=200),
        ),
    ]
