# Generated by Django 5.0.3 on 2025-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paid',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paid',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
