# Generated by Django 5.0.3 on 2025-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_cart_ordered_at_alter_paid_ordered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_point',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paid',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paid',
            name='ordered_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paid',
            name='paid_at',
            field=models.DateTimeField(),
        ),
    ]
