# Generated by Django 5.0.3 on 2025-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_product_location_product_pickup_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], default='none', max_length=100, verbose_name='Role'),
        ),
    ]
