# Generated by Django 5.0.3 on 2025-03-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_point',
        ),
    ]
