# Generated by Django 5.0.3 on 2025-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_product_location_remove_product_pickup_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
