# Generated by Django 5.0.3 on 2025-03-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default=1234, editable=False, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paid',
            name='product_id',
            field=models.CharField(default=123456, editable=False, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
