# Generated by Django 5.0.3 on 2025-03-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_cart_product_id_paid_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
