# Generated by Django 5.0.3 on 2025-03-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid',
            name='product_id',
        ),
    ]
