# Generated by Django 5.0.3 on 2025-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_paid_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bank_name',
            new_name='zone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Dire Dawa', 'Dire Dawa'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Sidama', 'Sidama'), ('SNNP', 'SNNP'), ('Somali', 'Somali'), ('Tigray', 'Tigray')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
