# Generated by Django 5.0.3 on 2025-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_bank_name_customuser_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
