# Generated by Django 5.0.3 on 2025-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_cart_transport_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
