# Generated by Django 5.0.3 on 2025-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_useractivitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='category',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('registered', 'Registered'), ('viewed_product', 'Viewed Product'), ('ordered_product', 'Ordered Product'), ('edited_profile', 'Edited Profile'), ('searched', 'Searched'), ('added_to_cart', 'Added to Cart'), ('removed_from_cart', 'Removed from Cart'), ('checked_out', 'Checked Out'), ('updated_password', 'Updated Password')], max_length=50),
        ),
    ]
