# Generated by Django 5.0.3 on 2025-05-13 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_useractivitylog_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='product',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('registered', 'Registered'), ('viewed_product', 'Viewed Product'), ('ordered_product', 'Ordered Product'), ('edited_profile', 'Edited Profile'), ('searched', 'Searched'), ('added_to_cart', 'Added to Cart'), ('removed_from_cart', 'Removed from Cart'), ('checked_out', 'Checked Out'), ('updated_password', 'Updated Password'), ('failed_login', 'Failed Login'), ('failed_checkout', 'Failed Checkout'), ('failed_registration', 'Failed Registration'), ('failed_password_update', 'Failed Password Update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
