# Generated by Django 5.0.3 on 2025-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_useractivitylog_additional_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='description',
            field=models.TextField(blank=True, default='Description not provided'),
        ),
    ]
