# Generated by Django 5.0.3 on 2025-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
