# Generated by Django 5.0.3 on 2025-05-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_cart_ordered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='product_id',
            field=models.CharField(default='PRODUCT', editable=False, max_length=15, unique=True),
        ),
    ]
