# Generated by Django 5.0.3 on 2025-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_cart_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='original_id',
            field=models.CharField(default='ORIGINAL', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default='PRODUCT', editable=False, max_length=50, unique=True),
        ),
    ]
