# Generated by Django 5.0.3 on 2025-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_cart_original_id_alter_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='original_id',
            field=models.CharField(default='ORIGINAL', editable=False, max_length=255),
        ),
    ]
