# Generated by Django 5.0.3 on 2025-05-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_cart_original_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='original_id',
            new_name='cart_id',
        ),
    ]
