# Generated by Django 5.0.3 on 2025-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_rename_original_id_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='CART', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default='PRODUCT', editable=False, max_length=50),
        ),
    ]
