# Generated by Django 5.0.3 on 2025-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_paid_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default='PRODUCT', editable=False, max_length=255),
        ),
    ]
