# Generated by Django 5.0.3 on 2025-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
