# Generated by Django 5.0.3 on 2025-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='product_id',
            field=models.CharField(default='PRODUCT', editable=False, max_length=255),
        ),
    ]
