# Generated by Django 5.0.3 on 2025-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('registered', 'Registered'), ('viewed_product', 'Viewed Product'), ('ordered_product', 'Ordered Product'), ('added_to_cart', 'Added to Cart'), ('removed_from_cart', 'Removed from Cart'), ('checked_out', 'Checked Out'), ('product_added', 'Product Added'), ('failed_login', 'Failed Login'), ('failed_checkout', 'Failed Checkout'), ('failed_registration', 'Failed Registration'), ('failed_password_update', 'Failed Password Update')], max_length=50),
        ),
    ]
